import { sql } from "drizzle-orm";
import {
  pgTable,
  uuid,
  date,
  integer,
  boolean,
  timestamp,
  text,
  unique,
  uniqueIndex,
  foreignKey,
  check,
  index,
} from "drizzle-orm/pg-core";

// auth-schema.ts is generated by `bunx auth@latest generate`. Do not hand-edit it.
export * from "./auth-schema";

import { sessions, users } from "./auth-schema";

export const dailyRecords = pgTable(
  "daily_records",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    date: date("date").notNull(),
    coreRoutineMaintained: boolean("core_routine_maintained").default(false).notNull(),
    routineLockedAt: timestamp("routine_locked_at", { withTimezone: true }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    unique("daily_records_user_id_date_unique").on(t.userId, t.date),
    unique("daily_records_user_id_id_unique").on(t.userId, t.id),
  ],
);

export const plannedTasks = pgTable(
  "planned_tasks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull(),
    dailyRecordId: uuid("daily_record_id").notNull(),
    priority: text("priority").notNull(),
    title: text("title").notNull(),
    completed: boolean("completed").default(false).notNull(),
    estimatedHours: integer("estimated_hours").default(1).notNull(),
  },
  (t) => [
    foreignKey({
      name: "planned_tasks_owner_record_fk",
      columns: [t.userId, t.dailyRecordId],
      foreignColumns: [dailyRecords.userId, dailyRecords.id],
    }).onDelete("cascade"),
    index("planned_tasks_user_id_daily_record_id_idx").on(t.userId, t.dailyRecordId),
    check("planned_tasks_priority_valid", sql`${t.priority} in ('A1', 'A2', 'B', 'C')`),
    check("planned_tasks_estimated_hours_range", sql`${t.estimatedHours} between 0 and 24`),
  ],
);

export const hourlyLogs = pgTable(
  "hourly_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull(),
    dailyRecordId: uuid("daily_record_id").notNull(),
    hourSlot: integer("hour_slot").notNull(),
    note: text("note").default("").notNull(),
    category: text("category"),

    taskId: text("task_id"),
  },
  (t) => [
    foreignKey({
      name: "hourly_logs_owner_record_fk",
      columns: [t.userId, t.dailyRecordId],
      foreignColumns: [dailyRecords.userId, dailyRecords.id],
    }).onDelete("cascade"),
    index("hourly_logs_user_id_daily_record_id_idx").on(t.userId, t.dailyRecordId),
    index("hourly_logs_user_id_task_id_idx")
      .on(t.userId, t.taskId)
      .where(sql`${t.taskId} is not null`),
    // Deliberately not widened with user_id: this is the upsert conflict target.
    unique("hourly_logs_record_hour_unique").on(t.dailyRecordId, t.hourSlot),
    check("hourly_logs_hour_slot_range", sql`${t.hourSlot} between 0 and 23`),
    check(
      "hourly_logs_category_valid",
      sql`${t.category} is null or ${t.category} in ('focus', 'admin', 'rest', 'wasted')`,
    ),
  ],
);

export const privateCommitments = pgTable(
  "private_commitments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    secret: text("secret").notNull(),
    status: text("status").default("active").notNull(),
    startedOn: date("started_on").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    unique("private_commitments_user_id_id_unique").on(t.userId, t.id),
    uniqueIndex("private_commitments_live_per_user_uidx")
      .on(t.userId)
      .where(sql`${t.status} <> 'ended'`),
    check("private_commitments_status_valid", sql`${t.status} in ('active', 'paused', 'ended')`),
    check(
      "private_commitments_ended_shape",
      sql`(${t.status} = 'ended') = (${t.endedAt} is not null)`,
    ),
    check(
      "private_commitments_secret_shape",
      sql`left(${t.secret}, 5) = 'etf1.' and length(${t.secret}) between 24 and 512`,
    ),
  ],
);

export const commitmentCheckIns = pgTable(
  "commitment_check_ins",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull(),
    commitmentId: uuid("commitment_id").notNull(),
    keptOn: date("kept_on").notNull(),
    checkedInAt: timestamp("checked_in_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    foreignKey({
      name: "commitment_check_ins_owner_fk",
      columns: [t.userId, t.commitmentId],
      foreignColumns: [privateCommitments.userId, privateCommitments.id],
    }).onDelete("cascade"),
    // This constraint is the duplicate-check-in barrier. Do not remove as redundant.
    unique("commitment_check_ins_commitment_kept_on_unique").on(t.commitmentId, t.keptOn),
    index("commitment_check_ins_user_id_kept_on_idx").on(t.userId, t.keptOn),
    index("commitment_check_ins_user_id_commitment_id_idx").on(t.userId, t.commitmentId),
  ],
);

export const reauthGrants = pgTable(
  "reauth_grants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    sessionId: uuid("session_id")
      .references(() => sessions.id, { onDelete: "cascade" })
      .notNull()
      .unique(),
    grantedAt: timestamp("granted_at", { withTimezone: true }).defaultNow().notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (t) => [index("reauth_grants_user_id_expires_at_idx").on(t.userId, t.expiresAt)],
);

export const reauthFailures = pgTable(
  "reauth_failures",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("reauth_failures_user_id_occurred_at_idx").on(t.userId, t.occurredAt)],
);
